# Generated by Django 4.1.7 on 2023-02-25 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employ_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employ',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20),
            preserve_default=False,
        ),
    ]
