# Generated by Django 4.1.7 on 2023-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_birthday_alter_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='profession',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('receptor', 'Receptor')], max_length=20),
        ),
    ]
