# Generated by Django 4.1.7 on 2023-02-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_appointment_doctor_patient_receptor_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('treated', 'Treated')], default='pending', max_length=20, null=True),
        ),
    ]
