# Generated by Django 4.1.7 on 2023-02-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_treatment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
