# Generated by Django 4.1.7 on 2023-02-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_appointment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('receptor', 'Receptor'), ('patient', 'Patient')], default='patient', max_length=20, null=True),
        ),
    ]
